// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stock.Service.Persistence.Context;

#nullable disable

namespace Stock.Service.Persistence.Migrations
{
    [DbContext(typeof(StockServiceContext))]
    [Migration("20260126204924_initialmigration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stock.Service.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7de2063-ab55-41cd-b0cf-564942a09fd0"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("017cddac-3e3f-4e94-84ac-47a15cc34bf1"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("ff1db935-247f-4a95-b397-dda19b46976f"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("bfd3f7f6-c0a6-4c03-b562-3594a9228d32"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("cb7a1a26-c504-46fb-ba3c-a8489d1591af"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("bfd3f7f6-c0a6-4c03-b562-3594a9228d32"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("Stock.Service.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("Stock.Service.Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("017cddac-3e3f-4e94-84ac-47a15cc34bf1"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("bfd3f7f6-c0a6-4c03-b562-3594a9228d32"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("Stock.Service.Domain.Entities.Account", b =>
                {
                    b.HasOne("Stock.Service.Domain.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Stock.Service.Domain.Entities.Owner", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
